---
title: Testing Statistical Graphics
author-list:
  - name: Emily Robinson
    dept: Statistics Department
    affiliation: CalPoly
    email: earobinson@huskers.unl.edu
  - name: Heike Hofmann
    dept: Statistics Department
    affiliation: Iowa State University
    email: hofmann@iastate.edu
  - name: Susan Vanderplas
    dept: Statistics Department
    affiliation: University of Nebraska, Lincoln
    email: svanderplas2@unl.edu

abstract: |
  We outline our process and common pitfalls for developing and testing human perception of statistical graphics. 
  Goal: Integrate information from the design of \cite{clusters,sineillusion,emily-diss,power}. 

category: Research
bib: refs.bib
bibstyle: class-info/abbrv-doi.bst
# csl: ieee-transactions-on-visualization-and-computer-graphics.csl
ieee-keywords: 
  - \CCScatTwelve{Human-centered computing}{Visu\-al\-iza\-tion}{Visualization design and evaluation methods}{}
  - \CCScatTwelve{Human-centered computing}{Visu\-al\-iza\-tion}{Empirical studies in visualization}{}
  - \CCScatTwelve{Human-centered computing}{Visu\-al\-iza\-tion}{Visualization application domains}{Scientific visualization}
  - \CCScatTwelve{Applied computing}{Physical sciences and engineering}{Mathematics and statistics}{}
firstsection: Introduction

link-citations: false

format:  
  pdf:
    keep-tex: true
    template-partials: [partials/doc-class.tex, partials/title.tex, partials/before-body.tex, partials/after-body.tex]

pdf-engine: pdflatex

date: last-modified
---

<!-- Importance of testing statistical graphics -->

Charts and data visualizations are primary methods of communicating scientific information to the public in what we typically hope is an easy-to-digest, visually attractive package.
There are many strategies for creating charts and graphs, from Tufte-esque minimalism\cite{tufte} to charts designed with extra imagery and aesthetic appeal that draw the viewer's attention and persist in memory\cite[Ch 3]{cairoFunctionalArtIntroduction2012}. 
For a specified type of data, there are also usually many different chart forms to display that data: for instance, if we have a set of categorical data and we wish to show the relative proportions of each category, we could do so using a stacked bar chart or the polar equivalent, a pie chart. 
There have been several attempts to list out all of the types of charts\cite{ribeccaSearchChartsData}, create a taxonomy of charts\cite{bertin1983semiology}, or even to classify charts using a domain-specific grammar; the grammar of graphics\cite{wilkinsonGrammarGraphics1999}. 
With all of the different design choices available, how are chart creators to know what is the best approach for communicating data to the appropriate audience? 




# Testing Methods and Engagement

Lineups
You Draw It
Direct Assessment


# Developing a Model
This is the single longest part of the entire testing process

## The Role of Simulation

## Selecting Parameters


# Gathering and Analyzing Additional Information

Calculator observations
Scratchpad
Explanation
Confidence Level
User Interactions
Browser fingerprints


# Pilot Testing and Quality Assurance

Test early, test often, and make sure you look at all of your plots!!!
If you're generating new data for each participant, be sure to save that data to a database so that you can at least see where/how things went wrong!

# Monitoring the Data

Use of pilot data to set up analysis documents, github actions and/or shiny dashboard to monitor incoming results.

Not necessarily important for small tests of limited duration, because data from e.g. prolific comes in so quickly. Server load is actually a much greater concern. 

# Building the Application
Shiny is awesome

# Analyzing the Data
Be prepared for surprises