---
title: "Revision Reviews"
format: html
---

# Reviewer: 1

## Comments to the Author(s)
I appreciate the thoughtful and thorough responses to the previous comments. I have no additional suggestions for this version.

# Reviewer: 2

## Comments to the Author(s)
The authors have largely addressed comments from the first review. The paper reads much stronger now. Well done to the authors.

## Wanted fixes

- It should be noted that the on page 3 (in diff.pdf), the authors make reference to a yet to be published article. Please remember to fix this before publication, or change it to “provided in a future article” if yet not available at the time of publication.
- Page 8 (in diff.pdf)-> “opimizing the model and generation method” -> more specificity needed — model and generation method for what? This looks like it’s the subject of Section 4, so just a mention that it’ll be covered in more detail in Section 4 would be helpful.
- Authors don’t mention pre-registration. Author themselves don’t seem to have done pre-registration in the past. I think it warrants a small mention as part of the protocol.
- “our visual system is optimised for identifying differences between groups” -> any citation to back-up this claim?
- “This ability can interfere with the natural to use the null sampling models” -> looks like a grammar issue — I don’t understand what the authors mean by “with the natural to use the null sampling models”.

## Minor

- Page 8 (in diff.pdf) -> “experiment structure” -> “experimental structure"
- Page 11 (in diff.pdf) -> “2x3x3” replace x with $\times$.
- Some of the citations need fixing for DOI as it contains prefix duplicates: "https://urldefense.com/v3/__https://doi.org/https:/*doi.org__;Lw!!PvXuogZ4sRB2p-tU!Cq6ylkfZW13S760wtA3vZIM5ImtHcC0SuhnWAXTDntbx8_ats4DGZjOjbbdP8BD98BtxElGHT_hAj_aLXbZhtDkY_SMUV-ARig$ "
